### PR TITLE
Added support for machines with no laser intensity control.

### PR DESCRIPTION
**Pull request by Rabter1**
To support machines, that have no intensity control of the laser power, i have made two changes. 

## First change: Added a laser cutoff Threshhold

Op Setting: Laser Power Cutoff - Default: 0

The trheshhold is important for raster images. Because of the jpeg fragmentation a tiny amount of black level would turn on the laser. Since there is no intensity control the output would be total black -> bad quality
With the new settings you have the possibillity to ignore grey shades. 
The amount can be controled in % where 0 is white (no change to previous behaviour (default) and 100 would be black.

I have two images that show, how the cutoff setting can be used to increase quality of laser outpu drastically.

This image shows the output as it is:
without CutOff

This image shows the output with the new cutoff setting and set to 10% cutoff. Everything below 10% black level. will cutoff laser power and force it to 0%. 
with CutOff

I believe this feature can also be very helpfull for machines with intensity control.

## Secons change: Added possibility to suppress intensity output in gcode

Op Setting and Machine Setting: Laser Intensity - Default: true

If set to false, it basically means, that your machine does not support intensity control of laser power. 
If this setting is disabled there will be no intensity values in gcode. 

#### Why is this necessary?

At least for me, my machine software: MACH3, controller: IP-M waits a tiny amount every time a code is called with "S" in it. 
This results in the machine stopping. 
The machine starts to jitter and is very slow while engraving. If the intensity settings are omitted, the machine runs fast and super smooth. Maybe other people have the same issue. 
They can disable this setting and can enjoy nice gcode out of the box. 

## Limitations - Known issues - Todo
When the setting "Burn White" is enabled in "Laser Raster", the Tool ON and Tool OFF is not beeing put into gcode. 
Instead the output is always Laser ON with power of 0%. For machines with no intensity control this is an issue.

The solution would be to listen to Laser Power values to turn on and off lasers and not to the movement method G1 G0. 
I might fix this issue in the future but dont know yet.

## I thought this is a TODO (but it is not):
I made a mistake while debugging. This is not a TODO. 
If value is not set it defaults to true which means there is no change to existing behaviour.
<del>
I am not able to edit the default machines.
 Since i added a new machine setting which defaults to true, i belive every machine template needs to be edited. I dont know which value is beeing used, if no value is set for ``machineLaserIntensity``
 See the screenshot.
</del>
 
Default machines

### CODE REVIEW

**Comment by easytarget** [comment]
Hi, Thanks for the PR!
..sorry slow reply, I'm having to ration my LW work at the moment, but this is not forgotten about and I'll see what I can do to pull it in, The brightness cutoff looks particularly useful. I need to think about the rest (just to make sure I understand it properly).

**Comment by easytarget** [comment]
Works as advertised :smile:
 
Thank you for this; and for integrating it nicely with the existing settings etc..  it adds some useful functionality.

I'll merge it to the main branch shortly; I'm going to tweak/clarify the description and help text for 'Laser Intensity' a bit, and then it will be in the 4.1 RC2.

**Comment by Rabter1** [comment]
Hey @easytarget.
I thought about it a litte and i dont know, if i am happy with the current solution.

I am talking about the Laser Intensity Support setting. 

I added it as machine Settings aswell as Operation Setting. 

I believe, that most users dont need this setting and might not even know what it means. (Since there is no explanation in operations menu)
Because of this, i believe it would be better to remove it out of operation settings. (UI Element)
Also: If your machine doesn't support intensity control than there would be no need to change this setting on an operations- basis. It doesn't make sence to activate the option in one operation but not in the other. It is rather a setting for your machine

I think it is enough to have the option available in machine Settings with an explanation. 
So most users dont have to bother when setting up an operation.

I can do the changes if you agree and want me to do it.

**Comment by easytarget** [comment]
You actually sort of read my mind there, but let me think on it before committing anything, i was thinking of a slightly different plan..

**Comment by easytarget** [comment]
Ok, I've created #5 for this, I'll add my quick text changes to the branch and strip the option from the job menu as you suggest; I agree it is out of place there.

**Comment by cprezzi** [comment]
@Rabter1 

About you first change:
Did you know that it was alredy possible to use the picture manipulation options in the "Laser Raster" operation to reduce the grayscale to only two values (black or white), by setting Grayscale=luma and Shades=2. Then you can use brightness to set the threshhold.

About your second change:
I think also this change would not be needed. If the firmware accepts comments in gcode, like marlin, smoothie and grbl with ; then you could just change the gcode setting for Laser Intensity to ; which would post the intensity at the end of a G1-G3 after ; as a comment.

**Pull request merged**
