### PR TITLE
Added Laser cut (unoptimized) to keep path vertex order.

### PR DESCRIPTION
**Pull request by harlock999**
Adding a new cutting option so the vertex order is preserved. This is useful when piercing is needed and the first vertex is where the piercing must happen.
Maybe someday we'll add a separate option for each processing selection (laser cut, fill, milling, etc) so different optimizers could be used such as TSP implementations, but before this happen this option is hopefully useful to users.

### CODE REVIEW

**Comment by easytarget** [comment]
ooh, this looks good.
Let me get #1 out of the way, I think there are file (but not code) conflicts.. then we can re-base and commit this.

**Comment by easytarget** [comment]
So, I've been thinking about this, it's good, and I'd like to extend it to inside and outside cutting too. 
The obvious way to do that is with an extra operation option, rather than with a new cut type.
- Current plan is to merge to a new branch in my repo and make changes for this there.

**Comment by easytarget** [comment]
And... just merged to the wrong branch. Damn.

**Comment by harlock999** [comment]
> So, I've been thinking about this, it's good, and I'd like to extend it to inside and outside cutting too. The obvious way to do that is with an extra operation option, rather than with a new cut type.
> 
> * Current plan is to merge to a new branch in my repo and make changes for this there.

Absolutely agree. Someday when the other pressing things are done, I'd like to see a drop-down to select which optimizer type to use, or disable any optimization.

**Pull request merged**
